//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Underwater"",
            ""id"": ""45f6156c-c0b0-4667-9fa5-ceb38f0c758a"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f4ba96c5-2c27-4eb6-b790-8f8180035ed2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Light"",
                    ""type"": ""Button"",
                    ""id"": ""bc0301ce-c179-4ed9-b7f4-6c422e814dfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Propulsion"",
                    ""type"": ""Button"",
                    ""id"": ""9de1ebf3-1dc9-4872-b9fa-c6fc5f7d76ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""387799e6-48e0-4bca-b1c7-230d3566af31"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""57a72a8e-aae4-44e5-adce-3aa0c6f68458"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c8e53672-a805-45c5-9656-767b757e1de5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b03fca1f-6395-4bef-a821-c1f9b66aac38"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""feab23fd-4c7b-4fd2-893a-397b9d9a191d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b744594d-6fe1-4560-a221-6e726e1f7882"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1d2853dc-7c4d-45f4-b33f-134610ce89cf"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7f51c6a-1324-419e-b02c-e93494493d29"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6750c1ba-557b-4ab3-a969-f734fffb2365"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Propulsion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abf957d2-12bd-4a32-9f89-7c1f8bf5d433"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Propulsion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Underwater
        m_Underwater = asset.FindActionMap("Underwater", throwIfNotFound: true);
        m_Underwater_Move = m_Underwater.FindAction("Move", throwIfNotFound: true);
        m_Underwater_Light = m_Underwater.FindAction("Light", throwIfNotFound: true);
        m_Underwater_Propulsion = m_Underwater.FindAction("Propulsion", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Underwater
    private readonly InputActionMap m_Underwater;
    private IUnderwaterActions m_UnderwaterActionsCallbackInterface;
    private readonly InputAction m_Underwater_Move;
    private readonly InputAction m_Underwater_Light;
    private readonly InputAction m_Underwater_Propulsion;
    public struct UnderwaterActions
    {
        private @PlayerControls m_Wrapper;
        public UnderwaterActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Underwater_Move;
        public InputAction @Light => m_Wrapper.m_Underwater_Light;
        public InputAction @Propulsion => m_Wrapper.m_Underwater_Propulsion;
        public InputActionMap Get() { return m_Wrapper.m_Underwater; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UnderwaterActions set) { return set.Get(); }
        public void SetCallbacks(IUnderwaterActions instance)
        {
            if (m_Wrapper.m_UnderwaterActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnMove;
                @Light.started -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnLight;
                @Light.performed -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnLight;
                @Light.canceled -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnLight;
                @Propulsion.started -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnPropulsion;
                @Propulsion.performed -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnPropulsion;
                @Propulsion.canceled -= m_Wrapper.m_UnderwaterActionsCallbackInterface.OnPropulsion;
            }
            m_Wrapper.m_UnderwaterActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Light.started += instance.OnLight;
                @Light.performed += instance.OnLight;
                @Light.canceled += instance.OnLight;
                @Propulsion.started += instance.OnPropulsion;
                @Propulsion.performed += instance.OnPropulsion;
                @Propulsion.canceled += instance.OnPropulsion;
            }
        }
    }
    public UnderwaterActions @Underwater => new UnderwaterActions(this);
    public interface IUnderwaterActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLight(InputAction.CallbackContext context);
        void OnPropulsion(InputAction.CallbackContext context);
    }
}
